### ISSUE TITLE
[Bug]: Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException:  Unsupported/Unknown Elasticsearch version [8.12.1].Highest supported version is [7.x]. You may need to upgrade ES-Hadoop.

### ISSUE THREAD

**Issue by Kosmas** [jaegertracing/spark-dependencies#137]
### What happened?

Trying to run the spark dependencies job there is an error about the version of Elasticsearch and that it needs to be < 8.

It seems there was an issue #126 (closed) that has solved the issue, but using the latest image tag does not seem to be working.

On the other hand using the forked image here https://github.com/vmaleze/spark-dependencies-es8/pkgs/container/spark-dependencies-es8 works as it should

### Steps to reproduce

1. Try to use the docker locally docker run -it --rm -e STORAGE=elasticsearch  jaegertracing/spark-dependencies /bin/bash
2. Export necessary environment variables to connect to Elasticsearch
3. Run the command to create the dependencies java ${JAVA_OPTS} -jar $APP_HOME/jaeger-spark-dependencies-0.0.1-SNAPSHOT.jar

### Expected behavior

To run the job and return successfully

24/03/25 09:28:24 INFO ElasticsearchDependenciesJob: Done, 21 dependency objects created

### Relevant log output

```shell
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported/Unknown Elasticsearch version [8.12.1].Highest supported version is [7.x].
You may need to upgrade ES-Hadoop.
```

### Jaeger backend version

v 1.54.0

### SDK

OpenTelemetry Java

### Stogage backend

Elasticsearch

### Operating system

Linux

### Deployment model

Kubernetes

**Comment by yurishkuro** [comment]
> but using the latest image tag does not seem to be working.

Are you loading it as `latest` or by specific version? `latest` could be stale in your environment (if you previously downloaded an older version).

**Comment by Kosmas** [comment]
@yurishkuro it is the latest one I've used, but I don't see any tags here.
Is there a specific version I could try with ?

**Comment by yurishkuro** [comment]
`
docker pull ghcr.io/jaegertracing/spark-dependencies/spark-dependencies@sha256:a1bfac7bae0826f878dcb62bafc8e7ff8a4df64be09393ea2dc895b32b24d0c7
`

**Comment by elMateso** [comment]
Hi, I have same problem. With latest tag is not posible run jobs and got same error. I have elastic 8.6.2. Forked image also worked me.

**Comment by LeoQuote** [comment]
Use `ghcr.io/jaegertracing/spark-dependencies/spark-dependencies:latest` instead of the on on docker.io , which is outdated for ages.

**Comment by Stevenpc3** [comment]
> Use `ghcr.io/jaegertracing/spark-dependencies/spark-dependencies:latest` instead of the on on docker.io , which is outdated for ages.

Then why not update the image on docker.io or move all images to ghcr.io?  Why are they split across different repositories?

**Comment by LeoQuote** [comment]
Thanks for raising this question but I don’t know the answer either, just proposing an alternative for people who would see this.

You can try to find out and even fix it.

**Comment by yurishkuro** [comment]
I assume this is resolved when using images from `ghcr.io`
