### ISSUE TITLE
How to set Spark's driver-memory

### ISSUE THREAD

**Issue by jukylin** [jaegertracing/spark-dependencies#17]
Run command:
`
 docker run -itd 
 --name=spark-dependencies 
 --env STORAGE=elasticsearch 
 --env ES_NODES=http://172.17.0.5:9200 
 jaegertracing/spark-dependencies
`

I Got that : 
ERROR SparkContext: Error initializing SparkContext.
java.lang.IllegalArgumentException: System memory 466092032 must be at least 471859200. Please increase heap size using the --driver-memory option or spark.driver.memory in Spark configuration.

In mac

**Comment by pavolloffay** [comment]
It looks like an environment issue. Could you please confirm how much memory is available to your docker containers?

**Comment by jukylin** [comment]
It work when I set docker memory 2.5G.

**Comment by liorco3000** [comment]
> It looks like an environment issue. Could you please confirm how much memory is available to your docker containers?

How much memory does it need to run ?, does it really need about 2.5Gi having the same issue OOM when running the spark-cron job

**Comment by pavolloffay** [comment]
memory requirements depend on how much data do you process. It's impossible to generalize.

**Comment by liorco3000** [comment]
I understand anyway to tweak this with driver-memory ?

**Comment by pavolloffay** [comment]
I am not sure what you mean? Assigning more memory to the k8s job didn't help?

**Comment by liorco3000** [comment]
Yes it did but only when adding 3G of memory:
resources:
  limits:
    cpu: 750m
    memory: 3Gi
  requests:
    cpu: 700m
    memory: 3Gi

**Comment by VenkataGuda19** [comment]
In standalone spark ,
When I'm running spark job in intellij

**Comment by VenkataGuda19** [comment]
I was getting same memory issue even though we increased drivery memory to 5g
My system ram is 16gb

**Comment by VenkataGuda19** [comment]
Thank you so much in advance

**Comment by pavolloffay** [comment]
> When I'm running spark job in intellij

Does intellij limit the memory in some cases? 

Could you please experiment and report back what memory configuration worked for you? And approximately how much data did you process?
