### ISSUE TITLE
Including external services as dependencies

### ISSUE THREAD

**Issue by bpot** [jaegertracing/spark-dependencies#28]
Is it possible to have external dependencies (e.g. databases or services that aren't internal) be part of the dependency graph?

I've tried setting a couple tags `peer.service = '<external-service>'` field and `span.kind = 'client'` but that doesn't seem to work.

**Comment by pavolloffay** [comment]
Dependencies are not derived from services stored in tags. 

If the peer service is not instrumented we could create a link based on this tag e.g. `span.process.serviceName` and `peer.service` tag. 

cc @yurishkuro

**Comment by yurishkuro** [comment]
@pavolloffay +1

**Comment by Etienne-Carriere** [comment]
I am currently working on this point and I propose to 
- add an argument to the command line --uninstrumented.dependencies.suffix.tag=<tag> . With it is present, it creates 'pseudo-service' when the span : 
* is a leaf (no children)
* is a client (span.kind = 'client')
* has the tag <tag> (as specified in commandline)
The 'pseudo-service' name is the value of the tag <tag>

**Comment by pavolloffay** [comment]
@Etienne-Carriere that is great, contributions are welcome!

First I would start simple and add only link if there is `peer.service` tag present in span tags. This way we comply with OT  spec.

**Comment by Etienne-Carriere** [comment]
OK for  peer.service use. I have a first version working internally but the PR will wait agreement of my employer.
