### ISSUE TITLE
All data isn't displayed real-time

### ISSUE THREAD

**Issue by wolfelven** [jaegertracing/spark-dependencies#30]
Command: STORAGE=cassandra CASSANDRA_KEYSPACE="jaeger_v1_local" java -jar jaeger-spark-dependencies/target/jaeger-spark-dependencies-0.0.1-SNAPSHOT.jar
when i check dependency in ui, i should do this command everytime that the datas will only to update

**Comment by pavolloffay** [comment]
It's a batch job by design. We do not support real-time (stream) based variant of this job.
