### ISSUE TITLE
STORAGE=cassandra java -jar jaeager-spark-dependencies.jar

### ISSUE THREAD

**Issue by litaiqing** [jaegertracing/spark-dependencies#46]
ERROR
STORAGE=cassandra java -jar jae**a**ger-spark-dependencies.jar

TRUE
STORAGE=cassandra java -jar jaeger-spark-dependencies.jar

**Comment by pavolloffay** [comment]
It took me a while to understand what are you trying to say. I have fixed the readme in https://github.com/jaegertracing/spark-dependencies/commit/bc5957e3f55b2eeda9bd0854191b39cd34d77ccb
