### ISSUE TITLE
Validate the kind of the span

### ISSUE THREAD

**Issue by Etienne-Carriere** [jaegertracing/spark-dependencies#49]
Currently the validation of the kind of the span is done on the following [method](https://github.com/jaegertracing/spark-dependencies/blob/master/jaeger-spark-dependencies-common/src/main/java/io/jaegertracing/spark/dependencies/SpansToDependencyLinks.java#L101) : 
* When at least one tag has client, it is considered as a client tag 
* When at least one tag has server, it is considered as a server tag 

I propose to only check span.kind according to opentracing specification (https://github.com/opentracing/specification/blob/master/semantic_conventions.md)

**Comment by pavolloffay** [comment]
Yes there is missing equals on the tag key `key.equals("span.kind") && ...`

A fix is welcome :)

**Comment by Etienne-Carriere** [comment]
I have fixes in internal but waited for agreement of my employer
