### ISSUE TITLE
Spark-dependencies fails to connect to a local cassandra

### ISSUE THREAD

**Issue by FrankEppinkMsg** [jaegertracing/spark-dependencies#57]
## Requirement - what kind of business use case are you trying to solve?

I am trying to have spark-dependencies connect to a local Cassandra database to get dependencies shown in Jaeger

## Problem - what in Jaeger blocks you from solving the requirement?

`docker run --env STORAGE=cassandra --env CASSANDRA_CONTACT_POINTS=localhost:9042 jaegertracing/spark-dependencies
`
fails with 

> "Failed to open native connection to Cassandra at {127.0.0.1}:9042"

Remarks:
- I can successfully connect to the jaeger_cassandra container and e.g. via cqlsh check that the table "jaeger_v1_dc1.dependencies" exist but is empty
- I checked the different options as described on
https://github.com/jaegertracing/spark-dependencies#cassandra
but found no way how to connect.

## Any open questions to address
Any help on how to solve or investigate the problem is appreciated.
Thanks

**Comment by FrankEppinkMsg** [comment]
Problem was fixed by doing proper "docker networking", now the connection is working, therefore closing this issue.

**Comment by singh-kamal** [comment]
Hi, I am facing the same issue. Can you pls help with the details on “docker networking” solution?

**Comment by singh-kamal** [comment]
@FrankEppinkMsg - Can you please help me with the solution you implemented to resolve this? Thanks in advance.
