### ISSUE TITLE
The ES index prefix delimiter : is deprecated in latest jaeger

### ISSUE THREAD

**Issue by coffin5257** [jaegertracing/spark-dependencies#61]
## Requirement - what kind of business use case are you trying to solve?
Analyze jaeger service dependency

## Problem - what in Jaeger blocks you from solving the requirement?
The ES index prefix delimiter : is deprecated in latest jaeger

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Fix it

**Comment by coffin5257** [comment]
And the delimiter in jaeger is `-` for span and service, but `:` in dependencies.

**Comment by pavolloffay** [comment]
It should be consistent for all indices, if it's not it's a bug

**Comment by coffin5257** [comment]
I found a [pr](https://github.com/jaegertracing/spark-dependencies/pull/52) is resolving this issue, sorry for the duplicated.

**Comment by pavolloffay** [comment]
np  I will have to look at this soon
