### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by DavitSo** [jaegertracing/spark-dependencies#62]
Hi All,
Sorry if I put in inappropriate place.
I want to build and install spark job in linux host and get this error 

------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] jaeger-spark-dependencies-parent ................... SUCCESS [ 20.764 s]
[INFO] jaeger-spark-dependencies-test ..................... SUCCESS [ 11.236 s]
[INFO] jaeger-spark-dependencies-common ................... SUCCESS [  1.166 s]
[INFO] jaeger-spark-dependencies-cassandra ................ FAILURE [ 13.869 s]
[INFO] jaeger-spark-dependencies-elasticsearch ............ SKIPPED
[INFO] jaeger-spark-dependencies .......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 47.205 s
[INFO] Finished at: 2019-03-13T11:27:30-04:00
[INFO] Final Memory: 50M/340M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project jaeger-spark-dependencies-cassandra: There are test failures.

**Comment by DavitSo** [comment]
Thanks in advance.

**Comment by DavitSo** [comment]
any update??

**Comment by pavolloffay** [comment]
hi @DavitSo, could you please add the whole log?  Tests require configured docker on your machine. If you want to just build it you can run `mvn clean install -DskipTests`

**Comment by DavitSo** [comment]
I want to compile and run it in linux host. Is it possible(running).

**Comment by DavitSo** [comment]
Build is succeed. Thanks.

**Comment by DavitSo** [comment]
but there is no jaeger-spark-dependencies.jar file.
and if I run in correct way?
STORAGE=cassandra CASSANDRA_COUNT_POINTS=my_host:9042  CASSANDRA_KEYSPACE=jaeger_v1_test java -jar jaeger-spark-dependencies.jar

**Comment by pavolloffay** [comment]
Look at target directory `jaeger-spark-dependencies/target`

**Comment by DavitSo** [comment]
There are 2 jar files
jaeger-spark-dependencies-0.0.1-SNAPSHOT.jar 
original-jaeger-spark-dependencies-0.0.1-SNAPSHOT.jar

**Comment by DavitSo** [comment]
Hi  @pavolloffay 
Is this expected result?

19/03/19 03:50:43 INFO CassandraDependenciesJob: Running Dependencies job for 2019-03-19T00:00Z: 1552953600000000 ? Span.timestamp 1553039999999999
19/03/19 03:50:43 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/03/19 03:51:23 INFO CassandraDependenciesJob: Storing dependencies into dependencies_v2
19/03/19 03:51:23 INFO CassandraDependenciesJob: Done, 4 dependency objects created

Thanks.

**Comment by pavolloffay** [comment]
There are two jars, the first one bundles also all the dependencies.

The result looks fine. It all depends on how much data do you have - in your case it created only 4 dependency objects.

**Comment by DavitSo** [comment]
ok thanks!!
I'll close issue.
