### ISSUE TITLE
Cannot show the middleware  in the topology

### ISSUE THREAD

**Issue by changjiang2016** [jaegertracing/spark-dependencies#69]
In the topology ,the middleware cannot show.Middleware, such as mysql, ActiveMQ, is very important for incoming and outgoing traffic. This project does not seem to include special middleware in the display area.Is there a good solution to achieve this goal?
In Addition,the Tags,which are user-defined annotation of spans in order to query, filter, and comprehend trace data, are flexible, loose, uncontrollable.Depends on Tags in the topology map, may not achieve results under certain circumstances.But I have no idea to build a topology map without relying on the tags of the opentracing framework.What do you suggest?

**Comment by pavolloffay** [comment]
This library provides only calculation mechanism for upstream jaeger project. How the graph is shown and what is shown is defined in Jaeger-ui and Jaeger upstreadm data model (dependencies).

In the dependencies graph only services are shown. So if your middleware (mysql) reports spans it will be shown. I understand that mysql is not usually instrumented and therefore does not report any spans. 

Not instrumented services can be shown using `peer.service=foo` tag. It was added in this PR https://github.com/jaegertracing/spark-dependencies/pull/56/files. This means that your mysql instrumentation will have to add this tag to spans it creates.
